"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "@/components/Nav";
import NavEditor from "@/components/NavEditor";
import { usePathname } from "next/navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0d1117]`}>
        {pathname === "/" ? (
          <Nav />
        ) : pathname === "/note-editor" ? (
          <NavEditor />
        ) : pathname == "/dashboard" ? (
          <Nav />
        ) : (
          <></>
        )}
        {children}
      </body>
    </html>
  );
}
